apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-wmih
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qmdr-tenant/rhtap-demo-app/hacbs-test-project-wmih@sha256:9174a7a6de6f351c4d858dda4ac29788d05914442a92bd2dc5a6eb010efe670d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
