apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wmih
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wmih
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wmih
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wmih
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wmih
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qmdr-tenant/rhtap-demo-app/hacbs-test-project-wmih@sha256:9174a7a6de6f351c4d858dda4ac29788d05914442a92bd2dc5a6eb010efe670d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
